---
- name: Install additional packages
  ansible.builtin.apt:
    name:
      # Disk Utils
      - parted
      - ntfs-3g
      - xfsprogs
      - dosfstools
      # Network
      - net-tools
      - iptables
      - ufw
      # Utils
      - jq
      - curl
      - wget
      - nano
      - rsync
      - htop
      - btop
      - git
      - gnupg
      - usbutils
      - moreutils
      - ncurses-term
      - util-linux-extra
      - python-is-python3
      - arch-install-scripts
      # extra
      - fish
      - fastfetch
      - apt-transport-https
      - debian-keyring
      - debian-archive-keyring
    state: present
    install_recommends: false
    update_cache: true

- name: Ensure en_US.UTF-8 locale is generated
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set English locale as default
  ansible.builtin.command: update-locale LANG=en_US.UTF-8
  changed_when: true

- name: Set timezone to UTC+8
  community.general.timezone:
    name: Asia/Shanghai

- name: GRUB defaults
  ansible.builtin.replace:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=".*"$'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
